### ISSUE TITLE
Coding Challenge of Recycler View

### ISSUE THREAD

**Issue by haricodeharan** [google-developer-training/android-fundamentals#9] opened 2018-07-26 12:13 UTC
Challenge: Creating a click listener for each item in the list is easy, but it can hurt the performance of your app if you have a lot of data. Research how you could implement this more efficiently. This is an advanced challenge. Start by thinking about it conceptually, and then search for an implementation example.

I am not able to find an answer for this.

**Comment by haricodeharan** [comment] 2018-07-26 12:18
I dont know whether it can be considered as an issue or not.

**Comment by EricVanDerDijs** [comment] 2020-01-06 05:44
Hi, did you have any luck finding an answer to this?

**Comment by sholt6** [comment] 2021-01-03 15:35
I'm currently working on this course too and I did find a solution which works though I'm not certain I've actually completed the goal, which is to avoid performance issues by not assigning a click handler to every list item.

This solution involves assigning the click listener in the onBindViewHolder function, rather than in the WordViewHolder class definition. I removed some lines from said class definition (see commented-out lines):
```
class WordViewHolder extends RecyclerView.ViewHolder {

    public final TextView wordItemView;
    final WordListAdapter mAdapter;

    public WordViewHolder(View itemView, WordListAdapter adapter) {
        super(itemView);
        wordItemView = itemView.findViewById(R.id.word);
        this.mAdapter = adapter;
//        itemView.setOnClickListener(this);
    }

//    @Override
//    public void onClick(View view) {
//        int mPosition = getLayoutPosition();
//        String element = mWordList.get(mPosition);
//        mWordList.set(mPosition, "Clicked! " + element);
//        mAdapter.notifyDataSetChanged();
//    }
}
```
As said, I move this click listener into the onBindViewHolder method:
```
@Override
public void onBindViewHolder(@NonNull WordListAdapter.WordViewHolder holder, int position) {
    String mCurrent = mWordList.get(position);
    holder.wordItemView.setText(mCurrent);

    holder.itemView.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            int mPosition = holder.getLayoutPosition();
            String element = mWordList.get(mPosition);
            mWordList.set(mPosition, "Clicked! " + element);
            holder.mAdapter.notifyDataSetChanged();
        }
    });
}
```
While this does create an app which works as intended, I'm not certain that it fulfils the challenge requirement. The actual purpose of the onBindViewHolder method is to do the actual recycling of the RecyclerView - it refits each view with new data as and it comes to be displayed on-screen. I think this therefore means that each view is still being assigned its own click handler, in which case I think this doesn't meet the challenge requirements.
I'm not sure what the alternative would be though. There needs to be some function which responds individually to clicks on a given TextView, and so this must be done from the TextView in question, surely? I suppose as long as we're thinking through these issues, we can't be said to be entirely failing the challenge.

**Comment by Pranusha-Divakar** [comment] 2022-05-27 04:10
The method onBindViewHolder is called every time when you bind your view with object which just has not been seen. And every time you will add a new listener.
Instead what you should do is, attaching click listener on onCreateViewHolder.

    @Override
    public WordListAdapter.WordViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View mItemView = mInflater.inflate(R.layout.wordlist_item,
                parent, false);
        final WordViewHolder holder = new WordViewHolder(mItemView, this);
        holder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                int mPosition = holder.getLayoutPosition();
                // Use that to access the affected item in mWordList.
                String element = mWordList.get(mPosition);
                // Change the word in the mWordList.
                mWordList.set(mPosition, "Clicked! " + element);
                // Notify the adapter that the data has changed so it can
                // update the RecyclerView to display the data.
                holder.mAdapter.notifyDataSetChanged();
            }
        });
        return holder;
    }

**Closed as completed** 2023-07-24 20:09 UTC
